#!/bin/sh
# Simple wraper to launch python application from desired place.
cd ~/Python/pyGTKtalog/mvc
#export PYTHONPATH="$PYTHONPATH:/usr/lib/gajim"
#exec python -OO pyGTKtalog.py $@
exec python pygtktalog.py $@
